name: Deploy Festa Junina

on:
  push:
    branches:
      - main  # Executa toda vez que você enviar código para a branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Inspecionar o código
        uses: actions/checkout@v4

      - name: Injetar as URLs Secretas no HTML
        run: |
          sed -i 's|__URL_MAE__|${{ secrets.URL_MAE }}|g' junina/index.html
          sed -i 's|__URL_LEITURA__|${{ secrets.URL_LEITURA }}|g' junina/index.html

      - name: Publicar no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: junina # Define a pasta 'junina' como o site final
          branch: gh-pages # Branch que o GitHub Pages vai usar para exibir o site
